spring:
  application:
    name: czb

  #数据库配置
  datasource:
    #    url: jdbc:mysql://${MYSQL_URL:172.16.43.86:9525/${MYSQL_DATABASE:czb}}?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&useSSL=false
    #    username: ${MYSQL_USER:czb_user}
    #    password: ${MYSQL_PASS:Q@iG4#6F}

    #    url: jdbc:mysql://${MYSQL_URL:121.41.9.13:9525/${MYSQL_DATABASE:czb}}?allowMultiQueries=true&characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&useSSL=false
    #    username: ${MYSQL_USER:tempRoot}
    #    password: ${MYSQL_PASS:8kkC&25%}


    url: jdbc:mysql://${MYSQL_URL:39.98.250.45:3306/${MYSQL_DATABASE:czb}}?allowMultiQueries=true&characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:G@6tSRWx}

    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    type: redis
  redis:
    #    host: 172.16.43.86
    #    port: 5259
    #    password: r2Z0@WJM
    host: localhost
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 200
        max-wait: 2000
        test-on-borrow: true
        max-idle: 100

  activiti:
    check-process-definitions: false

  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    async:
      request-timeout: 10000

server:
  port: 8899
#  http:
#    port: 8899
#  ssl:
#    key-store: classpath:2233184__renduoduo2019.com.jks
#    key-store-type: PKCS12
#    key-store-password: 4wk1P81U
#    key-alias: alias


##端口号
#server.port: 888
#server.http.port: 8899
##你生成的证书名字
#server.ssl.key-store: classpath:tomcat.keystore
##密钥库密码
#server.ssl.key-store-password: 123456
#server.ssl.keyStoreType: JKS
#server.ssl.keyAlias: tomcat

flyway:
  baseline-on-migrate: true
  validate-on-migrate: false

logging:
  level:
    org:
      springframework: WARN
    com:
      cqut:
        czb:
          bn:
            dao: DEBUG

jwt:
  token_header: Authorization
  token_prefix: Bearer
  secret: cqut.czb
  iss: echisan
  expiration: 3600
  expiration_prmember: 604800