spring:
  application:
    name: czb

  #数据库配置
  datasource:
    #    链接正式服
#    url: jdbc:mysql://${MYSQL_URL:172.16.43.86:9525/${MYSQL_DATABASE:czb}}?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&useSSL=false
#    username: ${MYSQL_USER:czb_user}
#    password: ${MYSQL_PASS:Q@iG4#6F}

    #    本地链接正式服
    url: jdbc:mysql://${MYSQL_URL:121.41.9.13:9525/${MYSQL_DATABASE:czb}}?allowMultiQueries=true&characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&useSSL=false
    username: ${MYSQL_USER:tempRoot}
    password: ${MYSQL_PASS:8kkC&25%}

    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    type: redis
  redis:
    host: 121.41.9.13
    port: 5259
    password: r2Z0@WJM
    jedis:
      pool:
        max-active: 200
        max-wait: 2000
        test-on-borrow: true
        max-idle: 100

  activiti:
    check-process-definitions: false

  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    async:
      request-timeout: 40000

server:
  port: 888
  http:
    port: 8090
  ssl:
    key-store: classpath:3855919__renduoduo2019.com.jks
    key-store-type: PKCS12
    key-store-password: RRWStzb6
    key-alias: alias

flyway:
  baseline-on-migrate: true
  validate-on-migrate: false

logging:
  level:
    org:
      springframework: WARN
    com:
      cqut:
        czb:
          bn:
            dao: DEBUG

jwt:
  token_header: Authorization
  token_prefix: Bearer
  secret: cqut.czb
  iss: echisan

  expiration: 3600
  expiration_prmember: 604800